### PR TITLE
Typography & cosmetic improvements

### PR DESCRIPTION
**Pull request by sbastn**
This PR improves the readability of the support pages by fixing a few annoyances reported on #87.

### Before
screen shot 2015-10-08 at 9 38 57 am

### After
screen shot 2015-10-08 at 11 00 08 am

### Highlights:

* Matches font stack from main app
* Matches colors from main 
* Clearer headings hierarchy
* Incresed font for easier reading.

### CODE REVIEW

**Comment by aeden** [comment]
:heart: - you make our corner of the web so much more beautiful.

Personally I am ready for you to :shipit: but I didn't review code (do I need to?)

**Comment by aeden** [comment]
Can you amend the screen shot to show what it looks like with the callouts?

**Comment by sbastn** [comment]
@aeden like this?
screen shot 2015-10-08 at 11 06 18 am

**Comment by aeden** [comment]
That works, thanks. It was really just the part about the "When you add your domain name..." callout at the bottom. I wanted to see if that had been tweaked.

**Comment by sbastn** [comment]
I am playing with "When you add your domain name..."  now. I am not sure if I'll change it yet. Will keep you posted.

**Comment by sbastn** [comment]
I finally styled the callouts:

### Before
screen shot 2015-10-08 at 11 37 21 am
screen shot 2015-10-08 at 11 37 17 am
screen shot 2015-10-08 at 11 36 59 am

### After

screen shot 2015-10-08 at 11 35 29 am
screen shot 2015-10-08 at 11 26 09 am
screen shot 2015-10-08 at 11 36 35 am

**Comment by weppos** [comment]
Nice! :+1: You may also want to review the design effort I put on [dnsimple-developer](https://github.com/aetrion/dnsimple-developer) :D

**Pull request merged**
