### PR TITLE
Image optimization

### PR DESCRIPTION
**Pull request by sbastn**
Based on #138, this PR adds a rake task to optimize all images before we publish the site. It takes 15 seconds or so to complete the task on my machine. I was able to get it down from 10 minutes by removing a few compression workers that we don't need.

### CODE REVIEW

**Comment by jcaudle** [comment]
I wonder if this wouldn't be better as something we check with Travis and fail the build if the images could be optimized? I don't know how feasible that is with the tooling at hand, but It could help keep the repo slimmer if we fixup (via a rebase) commits with large images in them as well.

**Comment by jcaudle** [comment]
> fixup (via a rebase)

Obviously, this would only be something worth doing going forward. I don't think we really want to do this on all of our history...

**Comment by sbastn** [comment]
@jcaudle I'll merge this PR and we can hook this with Travis if we want to. If a slimmer repository is worth the effort, I can run it manually against the repo right now until we figure out a better solution.

**Comment by weppos** [comment]
@jcaudle altering the history of a published repo is never a good idea. Moreover, this repo is public, therefore you may end up causing a lot of trouble to people.

**Comment by weppos** [comment]
@sbastn attaching the task to the deploy means there may be side effects to the repo status (which means changes images) at the time of the deploy.

I suggest to keep the the task in rake and have all of us to be responsible of running it if we add images. In this way the image can be optimized *before* being committed. Otherwise, that will happen is that if 3 of us download the repo and deploy it, what will be deployed is not what we have in the repo.

**Comment by sbastn** [comment]
@weppos there are no change to the repository status because I am optimizing the `output/files` folder which is ignored.

I am OK with making this a manual task against the `content/files`. That's where I started originally.

**Comment by weppos** [comment]
@sbastn please also add a note to the README so that we remember to run the task. Actually... I suggest you to create a `CONTRIBUTING.markdown` file with the information about running the task. GitHub will prompt a reminder each time someone opens a PR.

**Comment by jcaudle** [comment]
> altering the history of a published repo is never a good idea

I agree. That's why I said it'd only be good to do the fixups on incoming commits. The point is moot however given the following clarification:

> there are no change to the repository status because I am optimizing the output/files folder which is ignored

I actually really like this method of optimizing. This allows us to have the higher quality images stored on the repo, but the optimized ones on the site. It also makes the Travis check I suggested, as well as a note on the readme, unnecessary. I say we :shipit:.

**Comment by sbastn** [comment]
I agree with your @jcaudle. 

Optimizing only the `output/files` before a deploy makes more sense for our setup. I'll revert back and ship this.

**Pull request merged**
