### PR TITLE
SPF article.

### PR DESCRIPTION
**Pull request by aeden**
This closes GH-147

### CODE REVIEW

**Comment by aeden** [comment]
Looking for :eyes: on this.

**Comment by sbastn** [comment]
:clap: :ship:

**Comment by weppos** [comment]
Great article. There are a couple of paragraphs I think would fit better as `warning` or `note`. Do you mind if I format them in the PR so that you can approve/reject them?

Also, in order to place the article after the other articles about the records, you should add the page name to the [article.yml](https://github.com/aetrion/dnsimple-support/blob/master/priorities/articles.yaml#L17) file.

screen shot 2015-12-31 at 16 46 35

(I think some of the articles above may need a cleanup at some point :blush: )

You also want to link the article from here http://support.dnsimple.com/articles/supported-dns-records/

**Comment by aeden** [comment]
> Do you mind if I format them in the PR so that you can approve/reject them?

Go for it.

**Comment by weppos** [comment]
@aeden done.

**Pull request merged**
