### PR TITLE
Label logo with support site and link back to app

### PR DESCRIPTION
**Pull request by sbastn**
This PR updates the top nav bar with:
* A support label, so it's clear where you are
* A 2x logo for those on those ridiculously nice looking high-dev screens
* A link back to the main app.

screen shot 2015-10-08 at 5 30 34 pm

### CODE REVIEW

**Comment by aeden** [comment]
:shipit:

**Comment by jacegu** [comment]
:+1: :clap: :shipit:

**Comment by Barbamama** [comment]
adding additional account  that sounds weird

adding more account

add another account

or something better

**Comment by jcaudle** [comment]
@Barbamama I made the change you suggested in 27c3fe2d9bac4e1aca8f4a4ee4008088de89eace.

**Comment by Barbamama** [comment]
Thank you!

**Pull request merged**
