### PR TITLE
Set up XML sitemap

### PR DESCRIPTION
**Pull request by jcaudle**
This will generate a sitemap every time we compile the site for publication.

### CODE REVIEW

**Comment by weppos** [comment]
:+1: You may want to add the location in the [`robots.txt` file](http://www.sitemaps.org/protocol.html#submit_robots).

**Comment by jcaudle** [comment]
We don't seem to have a robots.txt right now. I don't believe there's anything we want to disallow, correct?

**Comment by martinisoft** [comment]
@jcaudle Still good to have to let the bots know what is really crawl-able.

**Comment by weppos** [comment]
@jcaudle you can create a blank `robots.txt` with only the `Sitemap:` declaration. Search Engines will accept it.

**Comment by jcaudle** [comment]
Yep. I can get one added here and in aetrion/dnsimple-developer#24.

**Comment by weppos** [comment]
:metal:

**Pull request merged**
