### PR TITLE
Zone import article

### PR DESCRIPTION
**Pull request by sbastn**
This PR adds a new zone import article. Based on #19.

### CODE REVIEW

**Comment by weppos** [comment]
@sbastn I have the feeling that @jacegu may have come with a more comprehensive article in #101. Do you confirm we can use #101?

**Comment by sbastn** [comment]
Yep. Let's use #101

**Comment by jacegu** [comment]
So sorry about this man. Didn't notice there was a duplicate issue and we started working on the same thing.

**Comment by sbastn** [comment]
@jacegu no worries, we had 2 issues for this #10 and #19. I assigned #19 to myself without understanding that #10 was a kinda of duplicate.

Anyway, yours is better. You win, I win, we all win!

**Pull request closed without merging**
